# TCL File Generated by Component Editor 18.0
# Thu Dec 06 22:40:16 GMT+08:00 2018
# DO NOT MODIFY


# 
# QAM_Demodulation "QAM_Demodulation" v1.0
# CNLHC 2018.12.06.22:40:16
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module QAM_Demodulation
# 
set_module_property DESCRIPTION ""
set_module_property NAME QAM_Demodulation
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DigiC
set_module_property AUTHOR CNLHC
set_module_property DISPLAY_NAME QAM_Demodulation
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

