# TCL File Generated by Component Editor 16.1
# Sun Dec 09 19:22:12 GMT+08:00 2018
# DO NOT MODIFY


# 
# OFDM_ADC_Control "OFDM ADC Control" v1.0
# CNLHC 2018.12.09.19:22:12
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module OFDM_ADC_Control
# 
set_module_property DESCRIPTION ""
set_module_property NAME OFDM_ADC_Control
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DigiC/OFDM
set_module_property AUTHOR CNLHC
set_module_property DISPLAY_NAME "OFDM ADC Control"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL OFDM_ADC_Control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file OFDM_ADC_Control.v VERILOG PATH OFDM_ADC_Control.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point aso_out0
# 
add_interface aso_out0 avalon_streaming start
set_interface_property aso_out0 associatedClock clock_1
set_interface_property aso_out0 associatedReset reset
set_interface_property aso_out0 dataBitsPerSymbol 32
set_interface_property aso_out0 errorDescriptor ""
set_interface_property aso_out0 firstSymbolInHighOrderBits true
set_interface_property aso_out0 maxChannel 0
set_interface_property aso_out0 readyLatency 0
set_interface_property aso_out0 ENABLED true
set_interface_property aso_out0 EXPORT_OF ""
set_interface_property aso_out0 PORT_NAME_MAP ""
set_interface_property aso_out0 CMSIS_SVD_VARIABLES ""
set_interface_property aso_out0 SVD_ADDRESS_GROUP ""

add_interface_port aso_out0 aso_out0_data data Output 32
add_interface_port aso_out0 aso_out0_valid valid Output 1
add_interface_port aso_out0 aso_out0_endofpacket endofpacket Output 1
add_interface_port aso_out0 aso_out0_startofpacket startofpacket Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_1
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point clock_1
# 
add_interface clock_1 clock end
set_interface_property clock_1 clockRate 0
set_interface_property clock_1 ENABLED true
set_interface_property clock_1 EXPORT_OF ""
set_interface_property clock_1 PORT_NAME_MAP ""
set_interface_property clock_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_1 sampling_clk clk Input 1


# 
# connection point sample_control
# 
add_interface sample_control conduit end
set_interface_property sample_control associatedClock ""
set_interface_property sample_control associatedReset ""
set_interface_property sample_control ENABLED true
set_interface_property sample_control EXPORT_OF ""
set_interface_property sample_control PORT_NAME_MAP ""
set_interface_property sample_control CMSIS_SVD_VARIABLES ""
set_interface_property sample_control SVD_ADDRESS_GROUP ""

add_interface_port sample_control pre_sampling  pre_sample_control Input 1

# 
# connection point external_adc
# 
add_interface external_adc conduit end
set_interface_property external_adc associatedClock ""
set_interface_property external_adc associatedReset ""
set_interface_property external_adc ENABLED true
set_interface_property external_adc EXPORT_OF ""
set_interface_property external_adc PORT_NAME_MAP ""
set_interface_property external_adc CMSIS_SVD_VARIABLES ""
set_interface_property external_adc SVD_ADDRESS_GROUP ""

add_interface_port external_adc adc_data_Real RealData Input 14
add_interface_port external_adc adc_data_Imag ImagData Input 14
