# TCL File Generated by Component Editor 18.0
# Thu Dec 06 23:37:04 GMT+08:00 2018
# DO NOT MODIFY


# 
# OFDM_ADC_Control "OFDM ADC Control" v1.0
# CNLHC 2018.12.06.23:37:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module OFDM_ADC_Control
# 
set_module_property DESCRIPTION ""
set_module_property NAME OFDM_ADC_Control
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DigiC/OFDM
set_module_property AUTHOR CNLHC
set_module_property DISPLAY_NAME "OFDM ADC Control"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

