// ReceiverTopQsys_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module ReceiverTopQsys_mm_interconnect_1 (
		input  wire        clk_0_clk_clk,                              //                            clk_0_clk.clk
		input  wire        MMBridge_reset_reset_bridge_in_reset_reset, // MMBridge_reset_reset_bridge_in_reset.reset
		input  wire [9:0]  MMBridge_m0_address,                        //                          MMBridge_m0.address
		output wire        MMBridge_m0_waitrequest,                    //                                     .waitrequest
		input  wire [0:0]  MMBridge_m0_burstcount,                     //                                     .burstcount
		input  wire [3:0]  MMBridge_m0_byteenable,                     //                                     .byteenable
		input  wire        MMBridge_m0_read,                           //                                     .read
		output wire [31:0] MMBridge_m0_readdata,                       //                                     .readdata
		output wire        MMBridge_m0_readdatavalid,                  //                                     .readdatavalid
		input  wire        MMBridge_m0_write,                          //                                     .write
		input  wire [31:0] MMBridge_m0_writedata,                      //                                     .writedata
		input  wire        MMBridge_m0_debugaccess,                    //                                     .debugaccess
		output wire [0:0]  AvalonFIFO_out_address,                     //                       AvalonFIFO_out.address
		output wire        AvalonFIFO_out_read,                        //                                     .read
		input  wire [31:0] AvalonFIFO_out_readdata,                    //                                     .readdata
		input  wire        AvalonFIFO_out_waitrequest                  //                                     .waitrequest
	);

	wire         mmbridge_m0_translator_avalon_universal_master_0_waitrequest;   // AvalonFIFO_out_translator:uav_waitrequest -> MMBridge_m0_translator:uav_waitrequest
	wire  [31:0] mmbridge_m0_translator_avalon_universal_master_0_readdata;      // AvalonFIFO_out_translator:uav_readdata -> MMBridge_m0_translator:uav_readdata
	wire         mmbridge_m0_translator_avalon_universal_master_0_debugaccess;   // MMBridge_m0_translator:uav_debugaccess -> AvalonFIFO_out_translator:uav_debugaccess
	wire   [9:0] mmbridge_m0_translator_avalon_universal_master_0_address;       // MMBridge_m0_translator:uav_address -> AvalonFIFO_out_translator:uav_address
	wire         mmbridge_m0_translator_avalon_universal_master_0_read;          // MMBridge_m0_translator:uav_read -> AvalonFIFO_out_translator:uav_read
	wire   [3:0] mmbridge_m0_translator_avalon_universal_master_0_byteenable;    // MMBridge_m0_translator:uav_byteenable -> AvalonFIFO_out_translator:uav_byteenable
	wire         mmbridge_m0_translator_avalon_universal_master_0_readdatavalid; // AvalonFIFO_out_translator:uav_readdatavalid -> MMBridge_m0_translator:uav_readdatavalid
	wire         mmbridge_m0_translator_avalon_universal_master_0_lock;          // MMBridge_m0_translator:uav_lock -> AvalonFIFO_out_translator:uav_lock
	wire         mmbridge_m0_translator_avalon_universal_master_0_write;         // MMBridge_m0_translator:uav_write -> AvalonFIFO_out_translator:uav_write
	wire  [31:0] mmbridge_m0_translator_avalon_universal_master_0_writedata;     // MMBridge_m0_translator:uav_writedata -> AvalonFIFO_out_translator:uav_writedata
	wire   [2:0] mmbridge_m0_translator_avalon_universal_master_0_burstcount;    // MMBridge_m0_translator:uav_burstcount -> AvalonFIFO_out_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (10),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (10),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) mmbridge_m0_translator (
		.clk                    (clk_0_clk_clk),                                                  //                       clk.clk
		.reset                  (MMBridge_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (mmbridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (mmbridge_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (mmbridge_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (mmbridge_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (mmbridge_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (mmbridge_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (mmbridge_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (mmbridge_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (mmbridge_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (mmbridge_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (mmbridge_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (MMBridge_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (MMBridge_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (MMBridge_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (MMBridge_m0_byteenable),                                         //                          .byteenable
		.av_read                (MMBridge_m0_read),                                               //                          .read
		.av_readdata            (MMBridge_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (MMBridge_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (MMBridge_m0_write),                                              //                          .write
		.av_writedata           (MMBridge_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (MMBridge_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                           //               (terminated)
		.av_begintransfer       (1'b0),                                                           //               (terminated)
		.av_chipselect          (1'b0),                                                           //               (terminated)
		.av_lock                (1'b0),                                                           //               (terminated)
		.uav_clken              (),                                                               //               (terminated)
		.av_clken               (1'b1),                                                           //               (terminated)
		.uav_response           (2'b00),                                                          //               (terminated)
		.av_response            (),                                                               //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                           //               (terminated)
		.av_writeresponsevalid  ()                                                                //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (10),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) avalonfifo_out_translator (
		.clk                    (clk_0_clk_clk),                                                  //                      clk.clk
		.reset                  (MMBridge_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (mmbridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (mmbridge_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (mmbridge_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (mmbridge_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (mmbridge_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (mmbridge_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (mmbridge_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (mmbridge_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (mmbridge_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (mmbridge_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (mmbridge_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (AvalonFIFO_out_address),                                         //      avalon_anti_slave_0.address
		.av_read                (AvalonFIFO_out_read),                                            //                         .read
		.av_readdata            (AvalonFIFO_out_readdata),                                        //                         .readdata
		.av_waitrequest         (AvalonFIFO_out_waitrequest),                                     //                         .waitrequest
		.av_write               (),                                                               //              (terminated)
		.av_writedata           (),                                                               //              (terminated)
		.av_begintransfer       (),                                                               //              (terminated)
		.av_beginbursttransfer  (),                                                               //              (terminated)
		.av_burstcount          (),                                                               //              (terminated)
		.av_byteenable          (),                                                               //              (terminated)
		.av_readdatavalid       (1'b0),                                                           //              (terminated)
		.av_writebyteenable     (),                                                               //              (terminated)
		.av_lock                (),                                                               //              (terminated)
		.av_chipselect          (),                                                               //              (terminated)
		.av_clken               (),                                                               //              (terminated)
		.uav_clken              (1'b0),                                                           //              (terminated)
		.av_debugaccess         (),                                                               //              (terminated)
		.av_outputenable        (),                                                               //              (terminated)
		.uav_response           (),                                                               //              (terminated)
		.av_response            (2'b00),                                                          //              (terminated)
		.uav_writeresponsevalid (),                                                               //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                            //              (terminated)
	);

endmodule
